/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/debug.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/errorLog.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError0.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError10.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError11.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError12.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError13.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError14.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError15.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError16.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError17.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError18.txt
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError19.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError1.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError20.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError21.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError22.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError23.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError24.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError25.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError26.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError27.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError28.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError29.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError2.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError30.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError31.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError32.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError33.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError34.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError35.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError36.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError37.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError38.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError39.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError3.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError40.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError41.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError42.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError43.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError44.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError45.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError46.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError47.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError48.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError49.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError4.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError5.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError6.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError7.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError8.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/executionError9.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/inActive.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/newProducts.txt
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/pythonExecutionErrors.txt
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
/home/tupperware/JBHIFIWebCrawler/Debug/Archives/08-03-2017/results.txt
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
